AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
      - db/**/*
      - vendor/**/*
      - config.ru

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 32

Metrics/CyclomaticComplexity:
  Max: 10

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/DoubleNegation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 15

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: brackets

Style/SignalException:
  EnforcedStyle: semantic
